config/routes.rb
Cap3::Application.routes.draw do
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :description, :title
  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

def search
  @blogs = Blogs.search params[:search]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_banner.html.erb
<div id="banner">
	<div class="captions">
		<h2><%=image_tag 'capturing.png'%></h2>
	</div>
	<%=image_tag 'banner.jpg'%>
</div>
</div>

app/views/blogs/_baseline.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>
			Capture Art
		</title>
		<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="style2.css" />
	</head>
	<body>
		<div id="bg1"></div>
		<div id="bg2"></div>
		<div id="outer">
			<div id="header">
				<div id="logo">
					<h1>
						<a href="#"><img src="Capture_Art2.png" alt="capture chicago"/></a>
					</h1>
				</div>
				<div id="search">
					<form action="" method="post">
						<div>
							<input class="text" name="search" size="32" maxlength="64" />
						</div>
					</form>
				</div>
				<div id="nav">
					<ul>
						<li class="first">
							<a href="#">Home</a>
						</li>
						<li>
							<a href="#">Purchase Prints</a>
						</li>
						<li>
							<a href="#">Graphic Design Services</a>
						</li>
						<li>
							<a href="#">Mobile App</a>
						</li>
						<li>
							<a href="#">Blog</a>
						</li>
						<li>
							<a href="#">Portfolio</a>
						</li>
						<li>
							<a href="#">About</a>
						</li>
						<li class="last">
							<a href="#">Contact</a>
						</li>
					</ul><br class="clear" />
				</div>
			</div>
			<div id="banner">
				<div class="captions">
					<h2>capturing... one shot at a time</h2>
				</div>
				<img src="images/banner.jpg" alt="" />
			</div>
		
				</div>
				<div id="content">
					<div class="box">
						<h2>
							<strong>Capture of the Week </strong> - 
							<% @blogs.each do |blog| %>
							<%= blog.title %>
							
						</h2>
						<img src="app/assests/images/hankcock-300-tall.jpg" width="171" height="275" alt="" class="left" />
						<p>
							<%= blog.description.first%>
							
						<p></p>
						<p></p>
						<a href="http://www.freecsstemplates.org/">Link to Full Sized Image</a>
						<p></p>
						</p>
						
					</div>
					<div class="box">
						<h3>
							<strong>Capture of Last Week </strong> - Sears Tower, Chicago
						</h3>
						<img src="images/sears171.jpg" width="171" height="191" alt="" class="left" />
						<p>
							Here we have <strong>The Sears Tower</strong>, Here I wanted to experiment with various levels of light exposure.  As is
							my particular style, I opted for the the "overkill" light exposure.  So the Street lamps look like mini supernovas popping 
							out in front of the building in the background.  A little PhotoShop Layer FX and boom!
							<p></p>
							<p></p>
							<a href="http://www.freecsstemplates.org/">Link to Full Sized Image</a>
							<p></p>
						</p>
						<!-- <ul class="linkedList">
													<li class="first">
														<a href="#">Turpis et posuere urna dolor justo</a>
													</li>
													<li>
														<a href="#">Fringilla sem nisl purus lobortis magnis magna pellentesque</a>
													</li>
													<li>
														<a href="#">Venenatis magna ultricies sollicitudin sodales commodo nibh aenean</a>
													</li>
													<li>
														<a href="#">Magnis luctus penatibus non natoque nascetur tempus erat</a>
													</li>
													<li class="last">
														<a href="#">Penatibus dolor pharetra viverra ac erat proin</a>
													</li>
												</ul> -->
					</div><br class="clear" />
				</div><br class="clear" />
			</div>
		</div>
		<div id="copyright">
			&copy; CaptureArt.com <!-- Design and Photos by <a href="http://www.freecsstemplates.org/">Seth Epstein</a>. Photos by <a href="http://fotogrph.com/"></a>. -->
		</div>
	</body>
</html>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
<p>
<form method="POST" enctype="multipart/form-data" action="fup.cgi">
File to upload: <input type="file" name="upfile"><br>
<!-- Notes about the file: <input type="text" name="note"> --><br>
<br>
<!-- <input type="submit" value="Press"> to upload the file! -->
</form>
</p>  
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/_header.html.erb
	<head>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>
			Capture Art
		</title>
		<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="style2.css" />
	</head>
	<body>
		<div id="bg1"></div>
		<div id="bg2"></div>
		<div id="outer">
			<div id="header">
				<div id="logo">
					<h1>
						<a><%=image_tag 'Capture chicago-newfont2.png'%></a>
					</h1>
				</div>
									<div id="search">
										<form action="" method="post">
											<div>
												<input class="text" name="search" size="32" maxlength="64" />
												<!-- <%=image_tag 'search.png', :class =>"right" %> -->
											</div>
										</form>
						</div>
						<div id="nav">
							<ul>
								<li class="first">
									<%= link_to 'Home', blogs_path %>
								</li>
								|
								<li>
									<a href="#">Purchase Prints</a>
								</li>
								|
								<li>
									<a href="#">Graphic Design Services</a>
								</li>
								|
								<li>
									<a href="#">Mobile App</a>
								</li>
								|
								<li>
									<a href="#">Blog</a>
								</li>
								|
								<li>
									<a href="#">Portfolio</a>
								</li>
								|
								<li>
									<a href="#">About</a>
								</li>
								|
								<li class="last">
									<a href="#">Contact</a>
								</li>
							</ul><br class="clear" />
						</div>
					</div>
<p id="notice"><%= notice %></p>
<div id="banner">
	<div class="captions">
		<h2><%=image_tag 'capturing_shadow.png', :mouseover => "capturing_mouse.png" %></h2>
	</div>
	<%=image_tag 'banner_full.jpg'%>
</div>

app/views/blogs/_header2.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>
			Capture Art
		</title>
		<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="style2.css" />
	</head>
	<body>
		<div id="bg1"></div>
		<div id="bg2"></div>
		<div id="outer">
			<div id="header">
				<div id="logo">
					<h1>
						<a><%=image_tag 'capture-art-newfont.png'%></a>
					</h1>
				</div>
									<div id="search">
										<form action="" method="post">
											<div>
												<input class="text" name="search" size="32" maxlength="64" />
											</div>
										</form>
						</div>
						<div id="nav">
							<ul>
								<li class="first">
									<%= link_to 'Home', blogs_path %>
								</li>
								|
								<li>
									<a href="#">Purchase Prints</a>
								</li>
								|
								<li>
									<a href="#">Graphic Design Services</a>
								</li>
								|
								<li>
									<a href="#">Mobile App</a>
								</li>
								|
								<li>
									<a href="#">Blog</a>
								</li>
								|
								<li>
									<a href="#">Portfolio</a>
								</li>
								|
								<li>
									<a href="#">About</a>
								</li>
								|
								<li class="last">
									<a href="#">Contact</a>
								</li>
							</ul><br class="clear" />
						</div>
					</div>
<p id="notice"><%= notice %></p>

app/views/blogs/_sidebar.html.erb
	<div id="main">
		<div id="sidebar">
			<div class="box">
				<h3>
					Recent Photo Shoots
				</h3>
				<div class="dateList">
					<ul class="linkedList dateList">
						<li class="first">
							<span class="date">Oct 5</span> <a href="#">Chicago Night Walk</a>
						</li>
						<li>
							<span class="date">Oct 4</span> <a href="#">Chicago Cloud Gate</a>
						</li>
						<li>
							<span class="date">Jul 7</span> <a href="#">San Francisco Bridge</a>
						</li>
						<li>
							<span class="date">Jul 2</span> <a href="#">Ft Lauderdale Night Walk</a>
						</li>
						<li>
							<span class="date">Jun 28</span> <a href="#">Venice Beach</a>
						</li>
						<li class="last">
							<span class="date">Jun 24</span> <a href="#">Negril Fire Breather</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="box">
				<h3>
					Did <strong>you</strong> capture art?
				</h3>
				<p>
					<%= link_to 'Create New Post', new_blog_path %>
				</p>
			</div>
				</div>

app/views/blogs/edit.html.erb
<%= render 'header2' %>
<div id="main">
		<div class="box">

			<%=image_tag 'glostix_web.jpg', :width => "800" ,  :class =>"left" %>
			

<h1>Edit Capture Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

</div>
</div>

app/views/blogs/index.html.erb
<%= render 'header'%>
<%= render 'sidebar' %>				
<div id="content">
	<div class="box">

		<h2>
			<strong>Capture of the Week </strong> - <% @blogs.each do |blog| %>
				<%= blog.title %>
				<%end%>
		</h2>
		
		<%=image_tag 'hankcock_for_web.jpg', :size => "171x275" ,  :class =>"left" %>


		<% @blogs.each do |blog| %>

<p<%= blog.title %></p>
<p><%= blog.description %></p>
<p><%= link_to 'Link to Full Size Image', blog %></p>
<p><%= link_to 'Edit Image details', edit_blog_path(blog) %></p>
<p><%= link_to 'Delete Image', blog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<% end %>
		
		</table>
		
	</div>



<br />
	
	</div><br class="clear" />
</div><br class="clear" />
</div>
</div>
<div id="copyright">
&copy; CaptureArt.com 
</div>
</body>
</html>

app/views/blogs/new.html.erb
<%= render 'header2' %>
<%=image_tag 'fire_breather_crop.jpg', :width => "800" ,  :class =>"left" %>
<h1>New Capture Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<%= render 'header2'%>

<%=image_tag 'hankcock_for_web.jpg', :width => "800" ,  :class =>"left" %>
<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Description:</b>
  <%= @blog.description %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cap3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>